drop table managers;
create table managers
(
	man_id int not null primary key,
    man_name varchar(50) Not null,
    man_city varchar(50) not null,
    man_state varchar(50) not null
);

insert into managers(man_id,man_name,man_city,man_state)
values
(1149," Elara Moon","Agra","Uttar Pradesh"),
(1232," Caspian River","Ahmedabad","Gujarat"),
(2278," Jasper Willow","Allahabad","Uttar Pradesh"),
(1872," Lyra Night","Amritsar","Punjab"),
(1804," Ember Ash","Aurangabad","Maharashtra"),
(1339," Silas Storm","Bangalore","Karnataka"),
(2987," Luna Frost","Bhopal","Madhya Pradesh"),
(1952," Artemis Dawn","Chandigarh","Chandigarh"),
(1183," Zephyr Skye","Chennai","Tamil Nadu"),
(1218," Silas Breeze","Coimbatore","Tamil Nadu"),
(2140," River Wilde","Delhi","Delhi"),
(1680," Wren Ember","Dhanbad","Jharkhand"),
(2901," Corvus Stone","Faridabad","Haryana"),
(2856," Rowan Thorn","Ghaziabad","Uttar Pradesh"),
(2281," Sage Meadow","Guwahati","Assam"),
(2939," Cypress Moon","Gwalior","Madhya Pradesh"),
(3141," Aurora Star","Howrah","West Bengal"),
(2231," River Birch","Hubli-Dharwad","Karnataka"),
(2605," Sky Lark","Hyderabad","Telangana"),
(2527," Wilder Thorn","Indore","Madhya Pradesh"),
(1213," Wren Forest","Jabalpur","Madhya Pradesh"),
(2305," Phoenix Sun","Jaipur","Rajasthan"),
(1755," Wren Ember","Jodhpur","Rajasthan"),
(3207," Elara Willow","Kalyan-Dombivali","Maharashtra"),
(3188," Zephyr Skye","Kanpur","Uttar Pradesh"),
(1735," Jasper Ash","Kolkata","West Bengal Bengal"),
(3296," Luna Storm","Kota","Rajasthan"),
(1589," Caspian Frost","Lucknow","Uttar Pradesh"),
(1209," Phoenix Night","Ludhiana","Punjab"),
(2125," River Breeze","Meerut","Uttar Pradesh"),
(2467," Sage Sky","Mumbai","Maharashtra"),
(2865," Artemis Star","Nagpur","Maharashtra"),
(1324," Elara River","Nashik","Maharashtra"),
(1781," Wren Sun","Navi Mumbai","Maharashtra"),
(1622," Corvus Moon","Patna","Bihar"),
(1823," River Meadow","Pimpri-Chinchwad","Maharashtra"),
(2057," Luna Thorn","Pune","Maharashtra"),
(1474," Ember Moon","Raipur","Chhattisgarh"),
(2443," River Willow","Rajkot","Gujarat"),
(2992," Silas Night","Ranchi","Jharkhand"),
(1528," Aspen Forest","Solapur","Maharashtra"),
(2837," Wilder River","Srinagar","Jammu"),
(2508," Cypress Frost","Surat","Gujarat"),
(3085," Sage Birch","Thane","Maharashtra"),
(2577," River Sun","Vadodara","Gujarat"),
(3217," Corvus Storm","Varanasi","Uttar Pradesh"),
(1587," Silas Sky","Vasai-Virar","Maharashtra"),
(1718," Ember Thorn","Vijayawada","Andhra Pradesh"),
(1557," Lyra Breeze","Visakhapatnam","Andhra Pradesh");
